### PR TITLE
Add : Creating your first Smart Contract in Solidity

### LINKED ISSUE #100: Creating Your First Smart Contract with Solidity
# Title Of Blog Post : Creating Your First Smart Contract with Solidity

### PR DESCRIPTION
**Pull request by TIDYMOUSE**
# Title Of Blog Post :  Creating your first Smart Contract in Solidity
## Checklist
- [x]  Added Image For banner 
- [x]  Markdown file in the _posts directory following the naming convention
- [x]  Include Front Matter at the beginning of your Markdown file with metadata
- [x]  Testing Locally. This is very Important.

**This Pull request closes #100 **

### CODE REVIEW

**Review by TIDYMOUSE — COMMENTED** [review]
reviewed.

**Comment by TIDYMOUSE** [comment]
@holygrimm @darkbits018 @deep-Ak-47 please review this PR

**Comment by darkbits018** [comment]
Good one bro. Can you drop your email here so that I can send you a badge for contributing?

**Comment by TIDYMOUSE** [comment]
@darkbits018  you can mail on : 
advaityadav08@gmail.com

**Pull request merged**
